name: Continuous Deployment
on:
 # push:
 #   branches:
 #     - main
 workflow_dispatch:
 
jobs:
 checkout:
   runs-on: self-hosted
   steps:
     - uses: actions/checkout@v4
       name: checkout code from git

     - name: Deploy to K8s
       run: kubectl apply -f new-deployment.yaml 

     - name: list the deployment 
       run: kubectl get pods 
       
